version: '3.8'


services:
  db:
    image: postgres:16
    container_name: training_user_fastapi
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  bot-app:
    image: fastapi_training_user
    container_name: user
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    depends_on:
      - db
    ports:
      - '8000:8000'
    command: sh -c "alembic upgrade head"

volumes:
  db_data:

