"""NewModelUser

Revision ID: d1f28eed5e93
Revises: 64c4dd0f2dbe
Create Date: 2024-09-09 16:17:56.982436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1f28eed5e93'
down_revision: Union[str, None] = '64c4dd0f2dbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))
    op.drop_index('ix_users_family_name', table_name='users')
    op.drop_index('ix_users_given_name', table_name='users')
    op.create_index(op.f('ix_users_first_name'), 'users', ['first_name'], unique=False)
    op.create_index(op.f('ix_users_last_name'), 'users', ['last_name'], unique=False)
    op.drop_column('users', 'given_name')
    op.drop_column('users', 'family_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('family_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('given_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_last_name'), table_name='users')
    op.drop_index(op.f('ix_users_first_name'), table_name='users')
    op.create_index('ix_users_given_name', 'users', ['given_name'], unique=False)
    op.create_index('ix_users_family_name', 'users', ['family_name'], unique=False)
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
